import {MusicContainer} from 'containers/musicContainer';
import type {NextPage} from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>XITE Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MusicContainer />
    </>
  );
};

export default Home;
